package com.example.aichat.task.day3.reasoning.model;

/** One expert solution generated by the Day 3 expert-panel strategy. */
public record ExpertSolution(
        String role,
        String solution
) {
}
