import { expect, test } from '@playwright/test'

test('corpus, source modal, preview and navigation work', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Книга, которую можно проверить' })).toBeVisible()
  await page.locator('.document-item').first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Закрыть документ' }).click()
  await page.getByRole('button', { name: 'Разбиение и индексы' }).click()
  await page.getByRole('button', { name: 'Посмотреть чанки' }).click()
  await expect(page.locator('.chunk-card').first()).toBeVisible()
  await expect(page.getByText('Preview:', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: 'По структуре', exact: false }).click()
  await page.getByRole('button', { name: 'Посмотреть чанки' }).click()
  await expect(page.getByText('Предпросмотр: По структуре · 3000 / 300', { exact: true })).toBeVisible()
  await expect(page.locator('.chunk-card').first()).toBeVisible()
  await page.getByRole('button', { name: 'Сравнение стратегий' }).click()
  await expect(page.getByRole('heading', { name: 'Выберите два готовых индекса' })).toBeVisible()
  await page.getByRole('button', { name: 'Диагностический поиск' }).click()
  await expect(page.getByRole('heading', { name: 'Найдите фрагменты книги' })).toBeVisible()
})

test('mobile remains horizontally contained', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('.document-item').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/day21-mobile.png', fullPage: false })
  await page.getByRole('button', { name: 'Разбиение и индексы' }).click()
  await page.getByRole('button', { name: 'Посмотреть чанки' }).click()
  await expect(page.locator('.chunk-card').first()).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Сравнение стратегий' }).click()
  await page.locator('.index-option').filter({ hasText: 'Фиксированный размер' }).first().getByRole('checkbox').check()
  await page.locator('.index-option').filter({ hasText: 'По структуре' }).first().getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Сравнить индексы' }).click()
  await expect(page.locator('table')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('ready indices compare export and real search through UI', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Сравнение стратегий' }).click()
  await page.locator('.index-option').filter({ hasText: 'Фиксированный размер' }).first().getByRole('checkbox').check()
  await page.locator('.index-option').filter({ hasText: 'По структуре' }).first().getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Сравнить индексы' }).click()
  await expect(page.getByText('Одинаковый корпус и embedding space — сравнение допустимо.')).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать Markdown' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/\.md$/)
  await page.getByRole('button', { name: 'Диагностический поиск' }).click()
  await page.locator('.search-indexes label').filter({ hasText: 'Фиксированный размер' }).first().getByRole('checkbox').check()
  await page.locator('.search-indexes label').filter({ hasText: 'По структуре' }).first().getByRole('checkbox').check()
  await page.getByRole('textbox', { name: 'Ваш поисковый вопрос' }).fill('Чем отличаются reset --soft, --mixed и --hard?')
  await page.getByRole('button', { name: 'Найти в книге' }).click()
  await expect(page.locator('.search-columns > div')).toHaveCount(2, { timeout: 60_000 })
  await expect(page.locator('.search-hit')).toHaveCount(10)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: 'test-results/day21-search-desktop.png', fullPage: false })
  await page.getByRole('button', { name: 'Открыть сохранённый источник' }).first().click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('invalid overlap is explained and does not publish index', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Разбиение и индексы' }).click()
  await page.getByRole('spinbutton', { name: 'Перекрытие символов' }).fill('2000')
  await page.getByRole('button', { name: 'Посмотреть чанки' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await expect(page.locator('.chunk-card')).toHaveCount(0)
})

test('a delayed preview does not override user navigation', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Разбиение и индексы' }).click()
  await page.route('**/api/v1/preview', async route => {
    await new Promise(resolve => setTimeout(resolve, 400))
    await route.continue()
  })
  const previewRequest = page.waitForRequest(request => request.url().endsWith('/api/v1/preview'))
  const previewResponse = page.waitForResponse(response => response.url().endsWith('/api/v1/preview'))
  await page.getByRole('button', { name: 'Посмотреть чанки' }).click()
  await previewRequest
  await page.getByRole('button', { name: 'Диагностический поиск' }).click()
  await previewResponse
  await expect(page.getByRole('button', { name: 'Найти в книге' })).toBeEnabled()
  await expect(page.getByRole('heading', { name: 'Найдите фрагменты книги' })).toBeVisible()
})
