package com.example.mockgames;

import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/** Единственный владелец SQL-каталога: базовые игры дня 17 и вся история новых игр дня 18. */
@Repository
public class GameRepository {
    private final JdbcTemplate jdbc;

    public GameRepository(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
        initialize();
    }

    private void initialize() {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS seed_games (
                title VARCHAR(200) PRIMARY KEY,
                description VARCHAR(2000) NOT NULL
            )
            """);
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS generated_games (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(200) NOT NULL,
                genre VARCHAR(100) NOT NULL,
                description VARCHAR(2000) NOT NULL,
                created_at VARCHAR(40) NOT NULL
            )
            """);
        String[][] seeds = {
            {"Лунный архив", "Исследуйте заброшенную лунную станцию, расшифровывайте записи экипажа и восстанавливайте историю экспедиции."},
            {"Сад ветров", "Уютная игра о выращивании летающих растений и восстановлении островного сада."},
            {"Маяк на краю карты", "Приключение о смотрителе маяка, который прокладывает путь кораблям через загадочный туман."},
            {"Механика дождя", "Головоломка, где вы собираете машины для управления погодой в маленьком городе."},
            {"Звёздные тропы", "Экспедиция в космос по неизведанным планетам с исследованием древних сигналов."},
            {"Тихая библиотека", "Детективная история о библиотекаре, который ищет пропавшие книги и раскрывает тайны читателей."}
        };
        for (String[] game : seeds) {
            jdbc.update("MERGE INTO seed_games (title, description) KEY(title) VALUES (?, ?)", game[0], game[1]);
        }
    }

    /** Добавляет игру без удаления предыдущих записей; предел десяти относится только к сводке. */
    @Transactional
    public void addGenerated(String title, String genre, String description) {
        jdbc.update("INSERT INTO generated_games (title, genre, description, created_at) VALUES (?, ?, ?, ?)",
                title, genre, description, Instant.now().toString());
    }

    public List<Map<String, Object>> latest(long afterId, int limit) {
        return jdbc.query("""
            SELECT id, title, genre, description, created_at
            FROM generated_games WHERE id > ?
            ORDER BY id DESC LIMIT ?
            """, (rs, row) -> {
            Map<String, Object> game = new LinkedHashMap<>();
            game.put("id", rs.getLong("id"));
            game.put("title", rs.getString("title"));
            game.put("genre", rs.getString("genre"));
            game.put("description", rs.getString("description"));
            game.put("created_at", rs.getString("created_at"));
            return game;
        }, afterId, limit);
    }

    public long latestId() {
        return Objects.requireNonNullElse(jdbc.queryForObject(
                "SELECT MAX(id) FROM generated_games", Long.class), 0L);
    }

    public long generatedCount() {
        return jdbc.queryForObject("SELECT COUNT(*) FROM generated_games", Long.class);
    }

    public List<Map<String, String>> search(String query) {
        List<Map<String, String>> games = new ArrayList<>();
        jdbc.query("SELECT title, description FROM seed_games", rs -> {
            if (matches(query, rs.getString("title"), rs.getString("description"))) {
                games.add(Map.of("title", rs.getString("title"), "description", rs.getString("description")));
            }
        });
        jdbc.query("SELECT title, description FROM generated_games", rs -> {
            if (matches(query, rs.getString("title"), rs.getString("description"))) {
                games.add(Map.of("title", rs.getString("title"), "description", rs.getString("description")));
            }
        });
        return games;
    }

    private static boolean matches(String query, String title, String description) {
        String haystack = normalize(title + " " + description);
        return Arrays.stream(normalize(query).split("\\s+")).allMatch(haystack::contains);
    }

    private static String normalize(String value) {
        return value.toLowerCase(Locale.ROOT).replace('ё', 'е');
    }
}
