"""Порты памяти, позволяющие заменить SQLite без переноса правил агента."""
from typing import Protocol
from .models import MemoryCandidate, MemoryVersions, MemoryWorkspace, SaveMemory, StoredMessage
from agent_core.models import ConversationSummary
from capabilities.context_memory.models import ContextSettings


class MemoryWritePolicy(Protocol):
    """Предметные ограничения на поля и карточку задачи."""
    def validate_entry(self, candidate: MemoryCandidate) -> None: ...
    def validate_problem(self, problem: dict[str, str]) -> dict[str, str]: ...


class MemoryRepository(Protocol):
    """Атомарные операции над раздельными областями памяти."""
    async def create(self, agent_id: str, title: str, settings: ContextSettings, problem: dict[str, str]) -> ConversationSummary: ...
    async def source(self, agent_id: str, conversation_id: str, source_id: int) -> StoredMessage: ...
    async def source_index(self, agent_id: str, conversation_id: str, source_id: int) -> int: ...
    async def append_reply(self, workspace: MemoryWorkspace, reply: str) -> None: ...
    async def workspace(self, agent_id: str, conversation_id: str) -> MemoryWorkspace: ...
    async def save_entry(self, agent_id: str, conversation_id: str, command: SaveMemory) -> None: ...
    async def save_problem(self, agent_id: str, conversation_id: str, problem: dict[str, str], versions: MemoryVersions) -> None: ...
    async def delete_entry(self, agent_id: str, conversation_id: str, entry_id: str, versions: MemoryVersions) -> None: ...
    async def save_proposals(self, workspace: MemoryWorkspace, source_id: int, candidates: list[MemoryCandidate]) -> None: ...
    async def resolve(self, agent_id: str, conversation_id: str, proposal_id: str, action: str, versions: MemoryVersions) -> None: ...
