"""Порт атомарного хранения жизненного цикла без привязки к SQLite."""
from typing import Protocol
from .models import WorkflowWorkspace


class TaskUnitOfWork(Protocol):
    """Состояние, артефакт и событие фиксируются одной транзакцией."""
    async def workspace(self, agent_id: str, conversation_id: str) -> WorkflowWorkspace: ...
    async def change(self, agent_id: str, conversation_id: str, operation: str, command, policy): ...
    async def reserve(self, workspace, command, spec_id: str, limit: int | None): ...
    async def complete(self, workspace, command, result): ...
    async def fail(self, task_id: str, command_id: str, status: str = 'error'): ...
