/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCorpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewChunks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobs"];
        put?: never;
        post: operations["startJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndexes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes/{id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes/{id}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndexDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compareIndexes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchIndex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SourceFile: {
            path: string;
            sha256: string;
        };
        CorpusManifest: {
            corpusId: string;
            repository: string;
            revision: string;
            archiveSha256: string;
            license: string;
            attribution: string;
            selectedChapters: string[];
            files: components["schemas"]["SourceFile"][];
            resources?: components["schemas"]["SourceFile"][];
        };
        CorpusInfo: {
            snapshotId: string;
            manifest: components["schemas"]["CorpusManifest"];
            documentCount: number;
            sectionCount: number;
            characters: number;
            words: number;
            estimatedPages: number;
            pageFormula: string;
        };
        DocumentSection: {
            title: string;
            start: number;
            endExclusive: number;
        };
        TextBlock: {
            kind: string;
            start: number;
            endExclusive: number;
            sourceLine: number;
        };
        Document: {
            id: string;
            source: string;
            sourceUrl: string;
            title: string;
            chapter: string;
            text: string;
            sha256: string;
            sections: components["schemas"]["DocumentSection"][];
            blocks: components["schemas"]["TextBlock"][];
        };
        DocumentInfo: {
            id: string;
            title: string;
            chapter: string;
            source: string;
            characters: number;
            words: number;
            sections: number;
        };
        ChunkConfig: {
            /** @enum {string} */
            strategy: "FIXED" | "STRUCTURAL";
            maxCharacters: number;
            overlapCharacters: number;
        };
        Chunk: {
            chunkId: string;
            documentId: string;
            source: string;
            title: string;
            section: string;
            sections: string[];
            ordinal: number;
            start: number;
            endExclusive: number;
            sourceLineStart: number;
            sourceLineEnd: number;
            text: string;
            textSha256: string;
        };
        ChunkMetrics: {
            chunkCount: number;
            minCharacters: number;
            medianCharacters: number;
            p95Characters: number;
            maxCharacters: number;
            uniqueCharacters: number;
            indexedCharacters: number;
            coveragePercent: number;
            crossSectionChunks: number;
            splitCodeBlocks: number;
        };
        EmbeddingIdentity: {
            model: string;
            digest: string;
            dimension: number;
            templateVersion: string;
        };
        IndexInfo: {
            id: string;
            snapshotId: string;
            createdAt: string;
            config: components["schemas"]["ChunkConfig"];
            embedding: components["schemas"]["EmbeddingIdentity"];
            metrics: components["schemas"]["ChunkMetrics"];
            buildMilliseconds: number;
            embeddingMilliseconds: number;
            embeddingInputTokens: number | null;
            vectorBytes: number;
        };
        IndexJob: {
            id: string;
            config: components["schemas"]["ChunkConfig"];
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "READY" | "FAILED";
            processed: number;
            total: number;
            createdAt: string;
            updatedAt: string;
            indexId: string | null;
            error: string | null;
        };
        ChunkPreview: {
            snapshotId: string;
            config: components["schemas"]["ChunkConfig"];
            metrics: components["schemas"]["ChunkMetrics"];
            chunks: components["schemas"]["Chunk"][];
        };
        IndexComparison: {
            comparable: boolean;
            notes: string[];
            indexes: components["schemas"]["IndexInfo"][];
        };
        SearchRequest: {
            query: string;
            topK: number;
        };
        SearchHit: {
            rank: number;
            similarity: number;
            chunk: components["schemas"]["Chunk"];
        };
        SearchResult: {
            indexId: string;
            query: string;
            milliseconds: number;
            inputTokens: number | null;
            hits: components["schemas"]["SearchHit"][];
        };
        ApiError: {
            code: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCorpus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Корпус */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusInfo"];
                };
            };
        };
    };
    getDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"][];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    previewChunks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkConfig"];
            };
        };
        responses: {
            /** @description Preview без embeddings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPreview"];
                };
            };
        };
    };
    getJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задания */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJob"][];
                };
            };
        };
    };
    startJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkConfig"];
            };
        };
        responses: {
            /** @description Задание принято */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJob"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Прогресс */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJob"];
                };
            };
        };
    };
    getIndexes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готовые индексы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexInfo"][];
                };
            };
        };
    };
    getChunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Чанки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"][];
                };
            };
        };
    };
    getIndexDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документ сохранённого snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    compareIndexes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    indexIds: string[];
                };
            };
        };
        responses: {
            /** @description Сравнение */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexComparison"];
                };
            };
        };
    };
    searchIndex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Диагностический поиск, без LLM */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
        };
    };
}
