/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/grounded-answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateGroundedAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiments/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compareRetrievalModes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answer-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAnswerSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluation/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getControlQuestions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["generateAnswer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCorpus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["previewChunks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJobs"];
        put?: never;
        post: operations["startJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndexes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes/{id}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getChunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes/{id}/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIndexDocument"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compareIndexes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/indexes/{id}/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["searchIndex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GroundingRequest: {
            question: string;
            indexId: string;
            /** @default 10 */
            candidateTopK: number;
            /** @default 5 */
            finalTopK: number;
            /** @default 0.65 */
            similarityThreshold: number;
            /** @default 16000 */
            contextMaxCharacters: number;
            /** @default false */
            useRewrite: boolean;
            maxOutputTokens?: number | null;
        };
        /** @enum {string} */
        GroundedStatus: "ANSWERED" | "UNKNOWN" | "INVALID_EVIDENCE" | "ERROR";
        EvidenceSource: {
            chunkId: string;
            documentId: string;
            source: string;
            title: string;
            section: string;
        };
        VerifiedCitation: {
            source: components["schemas"]["EvidenceSource"];
            quote: string;
            startInChunk: number;
            endInChunkExclusive: number;
            canonicalStart: number;
            canonicalEndExclusive: number;
        };
        GroundedClaim: {
            text: string;
            citations: components["schemas"]["VerifiedCitation"][];
        };
        EvidenceIssue: {
            code: string;
            message: string;
            claimIndex: number | null;
            citationIndex: number | null;
        };
        GroundingRetrieval: {
            searchQuery: string;
            rawCandidates: components["schemas"]["SearchHit"][];
            selectedCandidates: components["schemas"]["SearchHit"][];
            decisions: components["schemas"]["CandidateDecision"][];
            included: components["schemas"]["SearchHit"][];
            omittedChunkIds: string[];
            textCharacters: number;
            milliseconds: number;
            embeddingInputTokens: number | null;
        };
        GroundingGeneration: {
            model: string;
            finishReason: string;
            milliseconds: number;
            usage: components["schemas"]["TokenUsage"] | null;
            estimatedCost: components["schemas"]["CostEstimate"] | null;
            messages: components["schemas"]["LlmMessage"][];
            rawJson: string;
        };
        /** @enum {string} */
        SupportCheckStatus: "PASSED" | "REJECTED" | "INVALID_RESPONSE";
        /** @enum {string} */
        ClaimSupportVerdict: "SUPPORTED" | "UNSUPPORTED" | "CONTRADICTED";
        ClaimSupportAssessment: {
            claimIndex: number;
            verdict: components["schemas"]["ClaimSupportVerdict"];
            reason: string;
        };
        ClaimSupportCheck: {
            status: components["schemas"]["SupportCheckStatus"];
            claims: components["schemas"]["ClaimSupportAssessment"][];
            issues: components["schemas"]["EvidenceIssue"][];
            generation: components["schemas"]["GroundingGeneration"];
        };
        /** @description One bounded semantic refinement. The rejected original draft and its judge remain unverified diagnostics; GroundedResult.generation/supportCheck describe the latest attempt. */
        GroundingRepair: {
            originalGeneration: components["schemas"]["GroundingGeneration"];
            originalSupportCheck: components["schemas"]["ClaimSupportCheck"];
        };
        GroundedResult: {
            request: components["schemas"]["GroundingRequest"];
            snapshotId: string;
            status: components["schemas"]["GroundedStatus"];
            answer: string;
            clarification: string | null;
            claims: components["schemas"]["GroundedClaim"][];
            sources: components["schemas"]["EvidenceSource"][];
            issues: components["schemas"]["EvidenceIssue"][];
            retrieval: components["schemas"]["GroundingRetrieval"] | null;
            rewrite: components["schemas"]["RewriteTrace"] | null;
            generation: components["schemas"]["GroundingGeneration"] | null;
            llmStagesAttempted: number;
            totalUsage: components["schemas"]["TokenUsage"] | null;
            estimatedCost: components["schemas"]["CostEstimate"] | null;
            totalMilliseconds: number;
            warnings: string[];
            supportCheck?: components["schemas"]["ClaimSupportCheck"] | null;
            /** @description Absent or null for older results and requests without semantic refinement. Its usage/cost already belong to the total. */
            repair?: components["schemas"]["GroundingRepair"] | null;
        };
        /** @enum {string} */
        RetrievalMode: "RAW" | "FILTERED" | "REWRITE" | "REWRITE_FILTERED";
        ExperimentRequest: {
            question: string;
            indexId: string;
            modes: components["schemas"]["RetrievalMode"][];
            candidateTopK: number;
            finalTopK: number;
            similarityThreshold: number;
            contextMaxCharacters: number;
            maxOutputTokens?: number | null;
            generateAnswers: boolean;
        };
        CandidateDecision: {
            hit: components["schemas"]["SearchHit"];
            /** @enum {string} */
            reason: "SELECTED" | "BELOW_THRESHOLD" | "TOP_K_LIMIT";
        };
        RetrievalTrace: {
            originalQuestion: string;
            searchQuery: string;
            filterApplied: boolean;
            thresholdApplied: number | null;
            rawCandidates: components["schemas"]["SearchHit"][];
            selectedCandidates: components["schemas"]["SearchHit"][];
            decisions: components["schemas"]["CandidateDecision"][];
            retrievalMilliseconds: number;
            embeddingInputTokens: number | null;
        };
        RewriteTrace: {
            query: string;
            model: string;
            finishReason: string;
            milliseconds: number;
            usage: components["schemas"]["TokenUsage"] | null;
            estimatedCost: components["schemas"]["CostEstimate"] | null;
            messages: components["schemas"]["LlmMessage"][];
            rawResponse: string;
        };
        ExperimentError: {
            code: string;
            message: string;
        };
        ExperimentResult: {
            mode: components["schemas"]["RetrievalMode"];
            /** @enum {string} */
            status: "ANSWERED" | "RETRIEVED" | "NO_CONTEXT" | "ERROR";
            message: string | null;
            error: components["schemas"]["ExperimentError"] | null;
            pipeline: components["schemas"]["RetrievalTrace"] | null;
            answer: components["schemas"]["AnswerResult"] | null;
            generationAttempted: boolean;
        };
        ExperimentComparison: {
            request: components["schemas"]["ExperimentRequest"];
            snapshotId: string;
            rewrite: components["schemas"]["RewriteTrace"] | null;
            rewriteError: components["schemas"]["ExperimentError"] | null;
            results: components["schemas"]["ExperimentResult"][];
            totalMilliseconds: number;
            llmStagesAttempted: number;
            totalUsage: components["schemas"]["TokenUsage"] | null;
            estimatedCost: components["schemas"]["CostEstimate"] | null;
            warnings: string[];
        };
        AnswerRequest: {
            question: string;
            /** @enum {string} */
            mode: "BASELINE" | "RAG";
            indexId?: string | null;
            topK: number;
            contextMaxCharacters: number;
            maxOutputTokens?: number | null;
        };
        LlmMessage: {
            role: string;
            content: string;
        };
        TokenUsage: {
            promptTokens: number;
            completionTokens: number;
            totalTokens: number;
            cacheHitTokens: number | null;
            cacheMissTokens: number | null;
        };
        CostEstimate: {
            minimumUsd: number;
            maximumUsd: number;
            source: string;
            verifiedOn: string;
            note: string;
        };
        AnswerContext: {
            indexId: string | null;
            snapshotId: string | null;
            retrievedCount: number;
            included: components["schemas"]["SearchHit"][];
            omittedChunkIds: string[];
            textCharacters: number;
            maxCharacters: number;
            retrievalMilliseconds: number;
            embeddingInputTokens: number | null;
        };
        AnswerResult: {
            id: string;
            createdAt: string;
            question: string;
            /** @enum {string} */
            mode: "BASELINE" | "RAG";
            model: string;
            temperature: number;
            thinking: string;
            answer: string;
            finishReason: string;
            truncated: boolean;
            maxOutputTokens: number | null;
            totalMilliseconds: number;
            generationMilliseconds: number;
            usage: components["schemas"]["TokenUsage"] | null;
            estimatedCost: components["schemas"]["CostEstimate"] | null;
            context: components["schemas"]["AnswerContext"];
            messages: components["schemas"]["LlmMessage"][];
            warnings: string[];
        };
        AnswerSettings: {
            configured: boolean;
            model: string;
            temperature: number;
            thinking: string;
            defaultContextMaxCharacters: number;
            maxOutputTokensDefault: number | null;
            priceSource: string;
        };
        ControlQuestion: {
            id: string;
            question: string;
            expected: string;
            expectedSourceSuffix: string;
            evidenceQuote: string;
        };
        SourceFile: {
            path: string;
            sha256: string;
        };
        CorpusManifest: {
            corpusId: string;
            repository: string;
            revision: string;
            archiveSha256: string;
            license: string;
            attribution: string;
            selectedChapters: string[];
            files: components["schemas"]["SourceFile"][];
            resources?: components["schemas"]["SourceFile"][];
        };
        CorpusInfo: {
            snapshotId: string;
            manifest: components["schemas"]["CorpusManifest"];
            documentCount: number;
            sectionCount: number;
            characters: number;
            words: number;
            estimatedPages: number;
            pageFormula: string;
        };
        DocumentSection: {
            title: string;
            start: number;
            endExclusive: number;
        };
        TextBlock: {
            kind: string;
            start: number;
            endExclusive: number;
            sourceLine: number;
        };
        Document: {
            id: string;
            source: string;
            sourceUrl: string;
            title: string;
            chapter: string;
            text: string;
            sha256: string;
            sections: components["schemas"]["DocumentSection"][];
            blocks: components["schemas"]["TextBlock"][];
        };
        DocumentInfo: {
            id: string;
            title: string;
            chapter: string;
            source: string;
            characters: number;
            words: number;
            sections: number;
        };
        ChunkConfig: {
            /** @enum {string} */
            strategy: "FIXED" | "STRUCTURAL";
            maxCharacters: number;
            overlapCharacters: number;
        };
        Chunk: {
            chunkId: string;
            documentId: string;
            source: string;
            title: string;
            section: string;
            sections: string[];
            ordinal: number;
            start: number;
            endExclusive: number;
            sourceLineStart: number;
            sourceLineEnd: number;
            text: string;
            textSha256: string;
        };
        ChunkMetrics: {
            chunkCount: number;
            minCharacters: number;
            medianCharacters: number;
            p95Characters: number;
            maxCharacters: number;
            uniqueCharacters: number;
            indexedCharacters: number;
            coveragePercent: number;
            crossSectionChunks: number;
            splitCodeBlocks: number;
        };
        EmbeddingIdentity: {
            model: string;
            digest: string;
            dimension: number;
            templateVersion: string;
        };
        IndexInfo: {
            id: string;
            snapshotId: string;
            createdAt: string;
            config: components["schemas"]["ChunkConfig"];
            embedding: components["schemas"]["EmbeddingIdentity"];
            metrics: components["schemas"]["ChunkMetrics"];
            buildMilliseconds: number;
            embeddingMilliseconds: number;
            embeddingInputTokens: number | null;
            vectorBytes: number;
        };
        IndexJob: {
            id: string;
            config: components["schemas"]["ChunkConfig"];
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "READY" | "FAILED";
            processed: number;
            total: number;
            createdAt: string;
            updatedAt: string;
            indexId: string | null;
            error: string | null;
        };
        ChunkPreview: {
            snapshotId: string;
            config: components["schemas"]["ChunkConfig"];
            metrics: components["schemas"]["ChunkMetrics"];
            chunks: components["schemas"]["Chunk"][];
        };
        IndexComparison: {
            comparable: boolean;
            notes: string[];
            indexes: components["schemas"]["IndexInfo"][];
        };
        SearchRequest: {
            query: string;
            topK: number;
        };
        SearchHit: {
            rank: number;
            similarity: number;
            chunk: components["schemas"]["Chunk"];
        };
        SearchResult: {
            indexId: string;
            query: string;
            milliseconds: number;
            inputTokens: number | null;
            hits: components["schemas"]["SearchHit"][];
        };
        ApiError: {
            code: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generateGroundedAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GroundingRequest"];
            };
        };
        responses: {
            /** @description Grounded result: читать status, UNKNOWN/INVALID/ERROR не являются доказанным ответом */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroundedResult"];
                };
            };
            /** @description Некорректные параметры */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Индекс отсутствует */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compareRetrievalModes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRequest"];
            };
        };
        responses: {
            /** @description Результаты режимов, общие стадии и независимые ошибки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentComparison"];
                };
            };
            /** @description Некорректная конфигурация */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Индекс отсутствует */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAnswerSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Публичные настройки генератора */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerSettings"];
                };
            };
        };
    };
    getControlQuestions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 10 evaluation cases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlQuestion"][];
                };
            };
        };
    };
    generateAnswer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerRequest"];
            };
        };
        responses: {
            /** @description Ответ и переданный контекст */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResult"];
                };
            };
            /** @description Параметры или бюджет некорректны */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Ошибка провайдера */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Генератор недоступен */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCorpus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Корпус */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusInfo"];
                };
            };
        };
    };
    getDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentInfo"][];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документ */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    previewChunks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkConfig"];
            };
        };
        responses: {
            /** @description Preview без embeddings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChunkPreview"];
                };
            };
        };
    };
    getJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Задания */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJob"][];
                };
            };
        };
    };
    startJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChunkConfig"];
            };
        };
        responses: {
            /** @description Задание принято */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJob"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Прогресс */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexJob"];
                };
            };
        };
    };
    getIndexes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Готовые индексы */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexInfo"][];
                };
            };
        };
    };
    getChunks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Чанки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Chunk"][];
                };
            };
        };
    };
    getIndexDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Документ сохранённого snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    compareIndexes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    indexIds: string[];
                };
            };
        };
        responses: {
            /** @description Сравнение */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexComparison"];
                };
            };
        };
    };
    searchIndex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Диагностический поиск, без LLM */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
        };
    };
}
