"""Порт профилей для замены SQLite без изменения агента и HTTP-контрактов."""
from typing import Protocol
from .models import CreateProfile, UpdateProfile, UserProfile


class ProfileRepository(Protocol):
    """Чтение и явная атомарная запись персональных предпочтений."""
    async def list(self) -> list[UserProfile]: ...
    async def get(self, profile_id: str) -> UserProfile: ...
    async def create(self, command: CreateProfile) -> UserProfile: ...
    async def update(self, profile_id: str, command: UpdateProfile) -> UserProfile: ...
